spring:
  data:
    mongodb:
      uri: mongodb://notification:notification@localhost:27017/notification-service?authSource=admin
  
  mongodb:
    embedded:
      enabled: false

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: WARN